services:
  backend:
    build: .
    container_name: loop-backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://neondb_owner:npg_exafjqoO4HQ7@ep-wild-paper-a2y3yrxv-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - SESSION_SECRET=aW3jk9XGzFsd7paS2kYnz4vBQKUbF6J7Eow5N4LZaAxJtH21i3bL4P8J3h9gH8g8n
      - CLOUDINARY_CLOUD_NAME=dpqyho229
      - CLOUDINARY_API_KEY=443841617795831
      - CLOUDINARY_API_SECRET=9N51vxq42CKcX1dUVIr-VRQ-bVQ

    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
