name: Loop CI

on:
  pull_request:
    branches:
      - development

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install front dependencies
        run: cd frontend && npm install

      - uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          browser: chrome
          headless: true

  unit-front-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd ./frontend && npm install && ./src/hooks && npm test

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd ./backend && npm install && npm test
